import { Hono } from "hono";
import type { AppEnv } from "../bindings";
import { optionalAuth } from "../middleware/auth";

const app = new Hono<AppEnv>();

/**
 * Generate a shell install script for a specific package.
 * GET /v1/install/:fullName
 *
 * For public packages: no token needed.
 * For private packages: CTX_TOKEN must be set when running the script.
 *
 * The generated script:
 * 1. Detects platform (darwin-arm64, linux-amd64, etc.)
 * 2. Uses CTX_TOKEN if set for auth
 * 3. Resolves the package version via the API
 * 4. Downloads the matching platform artifact (or default archive)
 * 5. Verifies SHA256 checksum
 * 6. Installs to ~/.ctx/packages/
 */
app.get("/v1/install/:scope/:name", optionalAuth, async (c) => {
  const scope = c.req.param("scope")!;
  const name = c.req.param("name")!;
  const fullName = `@${scope}/${name}`;
  const user = c.get("user");

  // Look up the package
  const pkg = await c.env.DB.prepare(
    "SELECT id, visibility, owner_type, owner_id, type FROM packages WHERE full_name = ? AND deleted_at IS NULL",
  ).bind(fullName).first();

  if (!pkg) {
    c.header("Content-Type", "text/plain; charset=utf-8");
    return c.body(`#!/bin/sh\necho "Error: package ${fullName} not found." >&2\nexit 1\n`, 404);
  }

  const isPrivate = pkg.visibility === "private";

  // Get latest version (including id for artifact lookup)
  const latest = await c.env.DB.prepare(
    "SELECT id, version, sha256, archive_sha256 FROM versions WHERE package_id = ? AND yanked = 0 ORDER BY created_at DESC LIMIT 1",
  ).bind(pkg.id).first<{ id: string; version: string; sha256: string; archive_sha256: string }>();

  if (!latest) {
    c.header("Content-Type", "text/plain; charset=utf-8");
    return c.body(`#!/bin/sh\necho "Error: no published versions for ${fullName}." >&2\nexit 1\n`, 404);
  }

  // Check if platform artifacts exist
  const artifactCount = await c.env.DB.prepare(
    "SELECT COUNT(*) as count FROM version_artifacts WHERE version_id = ?",
  ).bind(latest.id).first<{ count: number }>();
  const hasArtifacts = (artifactCount?.count ?? 0) > 0;

  // Build per-platform sha256 map for artifact verification
  let artifactShaMap: Record<string, string> = {};
  if (hasArtifacts) {
    const artifacts = await c.env.DB.prepare(
      "SELECT platform, sha256 FROM version_artifacts WHERE version_id = ?",
    ).bind(latest.id).all<{ platform: string; sha256: string }>();
    for (const a of artifacts.results ?? []) {
      artifactShaMap[a.platform] = a.sha256;
    }
  }

  // Only pass a valid archive hash (filter out backfill sentinels)
  const archiveSha = latest.archive_sha256 && latest.archive_sha256.length === 64
    ? latest.archive_sha256 : "";

  const apiBase = new URL(c.req.url).origin;
  const script = generateInstallScript(fullName, latest.version, archiveSha, apiBase, isPrivate, hasArtifacts, artifactShaMap);

  c.header("Content-Type", "text/plain; charset=utf-8");
  c.header("X-Content-Type-Options", "nosniff");
  c.header("Cache-Control", "public, s-maxage=300, stale-while-revalidate=600");
  return c.body(script);
});

function generateInstallScript(
  fullName: string,
  version: string,
  expectedSha256: string,
  apiBase: string,
  isPrivate: boolean,
  hasArtifacts: boolean,
  artifactShaMap: Record<string, string> = {},
): string {
  const escapedName = fullName.replace(/'/g, "'\\''");
  const escapedVersion = version.replace(/'/g, "'\\''");
  const encodedName = encodeURIComponent(fullName);

  return `#!/bin/sh
# Install script for ${escapedName}@${escapedVersion}
# Generated by getctx.org
set -eu

# ── Platform detection ──
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)         ARCH="amd64" ;;
  aarch64|arm64)  ARCH="arm64" ;;
  i386|i686)      ARCH="386" ;;
esac
PLATFORM="\${OS}-\${ARCH}"

echo "Installing ${escapedName}@${escapedVersion} for \${PLATFORM}..."

# ── Authentication ──
AUTH_HEADER=""
${isPrivate ? `if [ -z "\${CTX_TOKEN:-}" ]; then
  echo "Error: CTX_TOKEN is required to install private package ${escapedName}." >&2
  echo "Set it with: export CTX_TOKEN=<your-token>" >&2
  exit 1
fi` : `# Public package — token optional but enables private access if set.`}
if [ -n "\${CTX_TOKEN:-}" ]; then
  AUTH_HEADER="Authorization: Bearer \${CTX_TOKEN}"
fi

# ── Temp directory ──
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# ── Download ──
${hasArtifacts ? `# Platform-specific artifact available
DOWNLOAD_URL="${apiBase}/v1/packages/${encodedName}/versions/${escapedVersion}/artifacts/\${PLATFORM}"
FALLBACK_URL="${apiBase}/v1/packages/${encodedName}/versions/${escapedVersion}/archive"

# Per-platform SHA256 checksums
${Object.entries(artifactShaMap).map(([p, s]) => `ARTIFACT_SHA_${p.replace("-", "_")}="${s}"`).join("\n")}

# Try platform artifact first, fall back to default archive
USED_ARTIFACT=true
HTTP_CODE=$(curl -fsSL -w "%{http_code}" -o "$TMPDIR/pkg.tar.gz" \\
  ${isPrivate ? '-H "$AUTH_HEADER"' : '${AUTH_HEADER:+-H "$AUTH_HEADER"}'} \\
  "$DOWNLOAD_URL" 2>/dev/null) || true

if [ "$HTTP_CODE" != "200" ]; then
  echo "No artifact for \${PLATFORM}, trying default archive..."
  USED_ARTIFACT=false
  curl -fsSL -o "$TMPDIR/pkg.tar.gz" \\
    ${isPrivate ? '-H "$AUTH_HEADER"' : '${AUTH_HEADER:+-H "$AUTH_HEADER"}'} \\
    "$FALLBACK_URL"
fi` : `# Download default archive
USED_ARTIFACT=false
curl -fsSL -o "$TMPDIR/pkg.tar.gz" \\
  ${isPrivate ? '-H "$AUTH_HEADER"' : '${AUTH_HEADER:+-H "$AUTH_HEADER"}'} \\
  "${apiBase}/v1/packages/${encodedName}/versions/${escapedVersion}/archive"`}

# ── SHA256 verification ──
# Select the correct expected hash: artifact-specific or archive
EXPECTED_SHA=""
${hasArtifacts ? `if [ "$USED_ARTIFACT" = "true" ]; then
  # Look up the platform-specific SHA
  PLATFORM_VAR="ARTIFACT_SHA_$(echo "\${PLATFORM}" | tr '-' '_')"
  EXPECTED_SHA="$(eval echo "\\$\${PLATFORM_VAR}" 2>/dev/null)" || true
fi` : ""}
if [ -z "$EXPECTED_SHA" ]; then
  EXPECTED_SHA="${expectedSha256}"
fi
if command -v sha256sum >/dev/null 2>&1; then
  ACTUAL_SHA="$(sha256sum "$TMPDIR/pkg.tar.gz" | cut -d' ' -f1)"
elif command -v shasum >/dev/null 2>&1; then
  ACTUAL_SHA="$(shasum -a 256 "$TMPDIR/pkg.tar.gz" | cut -d' ' -f1)"
else
  echo "Warning: sha256sum/shasum not found, skipping verification." >&2
  ACTUAL_SHA=""
fi

if [ -n "$ACTUAL_SHA" ] && [ -n "$EXPECTED_SHA" ]; then
  if [ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]; then
    echo "Error: SHA256 mismatch!" >&2
    echo "  Expected: $EXPECTED_SHA" >&2
    echo "  Actual:   $ACTUAL_SHA" >&2
    exit 1
  fi
  echo "SHA256 verified: $ACTUAL_SHA"
fi

# ── Install ──
INSTALL_DIR="\${CTX_DATA_HOME:-\${XDG_DATA_HOME:-\$HOME/.ctx}}/packages/${escapedName}/${escapedVersion}"
mkdir -p "$INSTALL_DIR"
tar xzf "$TMPDIR/pkg.tar.gz" -C "$INSTALL_DIR"

# ── Symlink ──
CURRENT_LINK="$(dirname "$INSTALL_DIR")/current"
ln -snf "$INSTALL_DIR" "$CURRENT_LINK"

echo "Installed ${escapedName}@${escapedVersion} to $INSTALL_DIR"
echo "Done."
`;
}

export default app;
